# Generated by Django 5.1.5 on 2026-07-22 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_text', models.TextField()),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('exam_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_jobs', to='exams.examtype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('choices', models.JSONField(default=list)),
                ('correct_index', models.PositiveSmallIntegerField()),
                ('position', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('exam_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.examtype')),
            ],
            options={
                'ordering': ['position', 'id'],
                'indexes': [models.Index(fields=['exam_type', 'position'], name='question_exam_pos_idx')],
            },
        ),
    ]
